* Time while never come back

when I think good time, hard time, and eventually fun times.
it always come back those time will come back.
they grow distant and further from me on silver dime that spins 10s of luck.
I know those times are gone and life will go one.
it my time to eventually be done.
including those I love.

I am gone
and so will you

* fun terms

Bweare my LAZER PONIES! - DOG WITCH!

* quote

take your barons, 
take your floor, 
and go sit on it
cause you live in a place where nothing exist.

take your barons
take your land
I do not care
cause it is a place where no one want to live

jickery pockery I do not care
cause I am not here to cast spells
I am here to cast a mind
a mind of my own
To speak the problems we need to know

monery monery what is this place?
there so much debuchery in this public play.
I not here on what you should say.
I am here on what you should do.

duby noby on the fire,
soby woby on the dire,
wivy dovu on the cider
market bucket on the buyer
side side on the nation on fire

we got a cowboy on hat
we have a girl on fast
that's today politics

* good Pvz2 leves

Jurrassic Marsh
22

* predictions 2026

year
01 huge increase of measles
02 US riot
03 china stealing US tech
04 china treatens the US
05 Russia treatens the US/EU
06 memes about trump age
07 Iran callapsing
08 middle eastern war
09 african genocide
10 someone leaking from government
11 something epstein files
12 trump being force to do something
13 democrates taking majority senate/house
14 lawsuit against honey (again)
15 legislation digital applications
16 lawsuits against RFK
17 ukraine war continue beyond 2026
18 trump with ukraine war
19 trump humililates zelensky
20 supreme court making bad decisions
21 congress try impeach supreme court judge
22 congress surpass a veto
23 new war
24 ukraine making something revolutionary
25 ukraine helping taiwan

01- 02- 03- 04- 05-
06- 07- 08- 09- 10-
11- 12- 13- 14- 15-
16- 17- 18- 19- 20-
21- 22- 23- 24- 25-

future
01 russia losing russio-ukra war
02 russia engage short conflict with nato
03 


month 1
0 something healthcare
1 trump supporting russia
2 RFK not showing himself in public
3 Marker Rubio in the media
4 Media ignore ukraine
5 russian power plant destroyed
6 new naval drone revealed
7 600+ drone strike by russia
8 daily r/u 2000+
9 oil tanker destroyed/taken

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

month 2
0 russian radar/AAS destroyed
1 
2
3
4
5
6
7
8
9

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

month 3
0 
1 
2
3
4
5
6
7
8
9

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

month 4
0 
1 
2
3
4
5
6
7
8
9

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

month 5
0 
1 
2
3
4
5
6
7
8
9

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

month 6
0 
1 
2
3
4
5
6
7
8
9

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

month 7
0 
1 
2
3
4
5
6
7
8
9

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

month 8
0 
1 
2
3
4
5
6
7
8
9

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

month 9
0 
1 
2
3
4
5
6
7
8
9

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

month 10
0 
1 
2
3
4
5
6
7
8
9

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

month 11
0 
1 
2
3
4
5
6
7
8
9

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

month 12
0 
1 
2
3
4
5
6
7
8
9

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct

=============================================
month 
0 
1 
2 
3 
4 
5 
6 
7 
8 
9 

0- 1- 2- 3- 4- 5- 6- 7- 8- 9-
2 correct


